version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo "Installing dependencies..."
      - yum install -y httpd aws-cli

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - aws s3 cp s3://<your-s3-bucket-name>/index.html /tmp/index.html

  build:
    commands:
      - echo "Starting build phase..."
      - sudo mv /tmp/index.html /var/www/html/index.html
      - sudo chown apache:apache /var/www/html/index.html
      - sudo chmod 644 /var/www/html/index.html

  post_build:
    commands:
      - echo "Restarting Apache server to reflect changes..."
      - sudo systemctl restart httpd
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - '**/*'